# Generated by Django 3.0.5 on 2021-07-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acountapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='HelloWorld',
        ),
    ]
